name: Simple AI Bot
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and Run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          # आपण थेट एक साधी स्क्रिप्ट तयार करू जी एरर देणार नाही
          npm install telegraf @google/generative-ai
          
          echo "
          const { Telegraf } = require('telegraf');
          const { GoogleGenerativeAI } = require('@google/generative-ai');

          const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);
          const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
          const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

          bot.start((ctx) => ctx.reply('नमस्कार आदित्य! मी आता पूर्णपणे तयार आहे. विचारा काय विचारायचे आहे.'));

          bot.on('text', async (ctx) => {
              try {
                  const result = await model.generateContent(ctx.message.text);
                  const response = await result.response;
                  ctx.reply(response.text());
              } catch (e) {
                  ctx.reply('क्षस्व, काहीतरी तांत्रिक अडचण आली आहे.');
              }
          });

          bot.launch();
          console.log('Bot is running error-free...');
          " > index.js
          
          node index.js
          
