name: Aditya Royal Telegraf AI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and Run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          # Telegraf आणि Gemini AI लायब्ररी इन्स्टॉल करणे
          npm install telegraf @google/generative-ai
          
          # बॉटची नवीन स्क्रिप्ट तयार करणे
          echo "
          const { Telegraf } = require('telegraf');
          const { GoogleGenerativeAI } = require('@google/generative-ai');

          const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);
          const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
          const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

          bot.start((ctx) => ctx.reply('नमस्कार आदित्य! हा तुमचा नवीन Telegraf AI बॉट आहे. आता कोणतेही Unauthorized एरर येणार नाहीत.'));

          bot.on('text', async (ctx) => {
              try {
                  const result = await model.generateContent(ctx.message.text);
                  ctx.reply(result.response.text());
              } catch (e) {
                  ctx.reply('तांत्रिक अडचण आली आहे, पुन्हा प्रयत्न करा.');
              }
          });

          bot.launch();
          console.log('Telegraf Bot is running...');
          " > index.js
          
          node index.js
          
